// Generated by gencpp from file lino_msgs/Firmware.msg
// DO NOT EDIT!


#ifndef LINO_MSGS_MESSAGE_FIRMWARE_H
#define LINO_MSGS_MESSAGE_FIRMWARE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lino_msgs
{
template <class ContainerAllocator>
struct Firmware_
{
  typedef Firmware_<ContainerAllocator> Type;

  Firmware_()
    : command()
    , subcommand()
    , arg1(0.0)
    , arg2(0.0)
    , arg3(0.0)  {
    }
  Firmware_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , subcommand(_alloc)
    , arg1(0.0)
    , arg2(0.0)
    , arg3(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subcommand_type;
  _subcommand_type subcommand;

   typedef float _arg1_type;
  _arg1_type arg1;

   typedef float _arg2_type;
  _arg2_type arg2;

   typedef float _arg3_type;
  _arg3_type arg3;





  typedef boost::shared_ptr< ::lino_msgs::Firmware_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lino_msgs::Firmware_<ContainerAllocator> const> ConstPtr;

}; // struct Firmware_

typedef ::lino_msgs::Firmware_<std::allocator<void> > Firmware;

typedef boost::shared_ptr< ::lino_msgs::Firmware > FirmwarePtr;
typedef boost::shared_ptr< ::lino_msgs::Firmware const> FirmwareConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lino_msgs::Firmware_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lino_msgs::Firmware_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lino_msgs::Firmware_<ContainerAllocator1> & lhs, const ::lino_msgs::Firmware_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.subcommand == rhs.subcommand &&
    lhs.arg1 == rhs.arg1 &&
    lhs.arg2 == rhs.arg2 &&
    lhs.arg3 == rhs.arg3;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lino_msgs::Firmware_<ContainerAllocator1> & lhs, const ::lino_msgs::Firmware_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lino_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lino_msgs::Firmware_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lino_msgs::Firmware_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lino_msgs::Firmware_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lino_msgs::Firmware_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lino_msgs::Firmware_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lino_msgs::Firmware_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lino_msgs::Firmware_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca43ed677dd3e7e8e6f2d15da8ed4dd7";
  }

  static const char* value(const ::lino_msgs::Firmware_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca43ed677dd3e7e8ULL;
  static const uint64_t static_value2 = 0xe6f2d15da8ed4dd7ULL;
};

template<class ContainerAllocator>
struct DataType< ::lino_msgs::Firmware_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lino_msgs/Firmware";
  }

  static const char* value(const ::lino_msgs::Firmware_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lino_msgs::Firmware_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
"string subcommand\n"
"float32 arg1\n"
"float32 arg2\n"
"float32 arg3\n"
;
  }

  static const char* value(const ::lino_msgs::Firmware_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lino_msgs::Firmware_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.subcommand);
      stream.next(m.arg1);
      stream.next(m.arg2);
      stream.next(m.arg3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Firmware_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lino_msgs::Firmware_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lino_msgs::Firmware_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
    s << indent << "subcommand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subcommand);
    s << indent << "arg1: ";
    Printer<float>::stream(s, indent + "  ", v.arg1);
    s << indent << "arg2: ";
    Printer<float>::stream(s, indent + "  ", v.arg2);
    s << indent << "arg3: ";
    Printer<float>::stream(s, indent + "  ", v.arg3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINO_MSGS_MESSAGE_FIRMWARE_H
